name: CI Pipeline

on:
  push:
    branches:
      - kk-lq-15
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - "4444"
        options: --shm-size 2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Install dependencies
        run: npm ci

      - name: Run tests in Docker
        run: |
          docker-compose up -d
          sleep 10
          npm run test:docker

      - name: Generate Allure report
        run: |
          npm run allure:generate

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
